### PR TITLE
Added support for a `cwd` setting

### PR DESCRIPTION
**Pull request by fabiospampinato**
Fixes https://github.com/Tyriar/vscode-shell-launcher/issues/12

### CODE REVIEW

**Comment by Tyriar** [comment]
Thanks @fabiospampinato, sorry about the delay

**Comment by Tyriar** [comment]
@fabiospampinato does this work for you? Testing it out with:

```js
"shellLauncher.shells.osx": [
    {
      "shell": "/bin/bash",
      "label": "bash",
      "cwd": "/home/daimms/dev"
    }
]
```

I'm seeing a chdir error in the terminal and then this:

screen shot 2018-03-30 at 8 24 57 am

**Comment by fabiospampinato** [comment]
It wasn't working for me either beucase of https://github.com/Tyriar/vscode-shell-launcher/pull/18.

I think you're getting that error because `/home/daimms/dev` doesn't exists, should we check for that?

**Comment by Tyriar** [comment]
> I think you're getting that error because /home/daimms/dev doesn't exists

Oh yeah, I'm on my mac not Linux box, haha. It couldn't hurt to show a nicer error message.

**Comment by fabiospampinato** [comment]
> It couldn't hurt to show a nicer error message.

Perhaps this check should be added in VSC itself? 🤔

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/17450 :smile:

**Pull request merged**
